//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT242516005.Localization {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAT242516005.Localization.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   İşlemler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ad benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Hasta Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddNewPatient {
            get {
                return ResourceManager.GetString("AddNewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ana Sayfa benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AnaSayfa {
            get {
                return ResourceManager.GetString("AnaSayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başlangıç Saati benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BaslangicSaati {
            get {
                return ResourceManager.GetString("BaslangicSaati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doğum Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bitiş Saati benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BitisSaati {
            get {
                return ResourceManager.GetString("BitisSaati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Branş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Brans {
            get {
                return ResourceManager.GetString("Brans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tarih benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doktor Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DoktorListesi {
            get {
                return ResourceManager.GetString("DoktorListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doktor Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DoktorListesiNav {
            get {
                return ResourceManager.GetString("DoktorListesiNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doktoru Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DoktoruEkle {
            get {
                return ResourceManager.GetString("DoktoruEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Düzenle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Duzenle {
            get {
                return ResourceManager.GetString("Duzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bitiş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ad benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hakkında benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Hakkinda {
            get {
                return ResourceManager.GetString("Hakkinda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hastane Otomasyon benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HastaneOtomasyon {
            get {
                return ResourceManager.GetString("HastaneOtomasyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İptal benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Iptal {
            get {
                return ResourceManager.GetString("Iptal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlemler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Islemler {
            get {
                return ResourceManager.GetString("Islemler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Vardiya Kaydet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KaydetButon {
            get {
                return ResourceManager.GetString("KaydetButon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıtlı doktor bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KayitliDoktorYok {
            get {
                return ResourceManager.GetString("KayitliDoktorYok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soyad benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hasta Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PatientList {
            get {
                return ResourceManager.GetString("PatientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaydet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SilButon {
            get {
                return ResourceManager.GetString("SilButon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soyad benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Soyad {
            get {
                return ResourceManager.GetString("Soyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başlangıç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vardiya Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VardiyaBasligi {
            get {
                return ResourceManager.GetString("VardiyaBasligi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vardiya Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VardiyaListesi {
            get {
                return ResourceManager.GetString("VardiyaListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Doktor Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YeniDoktorEkle {
            get {
                return ResourceManager.GetString("YeniDoktorEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Doktor Kaydı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YeniDoktorKaydi {
            get {
                return ResourceManager.GetString("YeniDoktorKaydi", resourceCulture);
            }
        }
    }
}
